name: McUtilities
main: ml.axegis.mcutilities.McUtilities
version: 1.0.1
author: Axegis
description: Utilities for minecraft
softdepend: [PlaceholderAPI]

commands:
  gms:
    description: Change to the survival mode.
    usage: /<command>
    permission: utilities.gm
  gma:
    description: Change to the adventure mode.
    usage: /<command>
    permission: utilities.gm
  gmc:
    description: Change to the creative mode.
    usage: /<command>
    permission: utilities.gm
  gmsp:
    description: Change to the spectator mode.
    usage: /<command>
    permission: utilities.gm
  fly:
    description: Enable and disable fly.
    usage: /<command>
    permission: utilities.fly
  utilities:
    description: Reload plugin config or see version
    usage: /<command>
    permission: utilities.utilities